# Shared constants, copied from  base.sdc  
set input_delay_value [ expr $::env(CLOCK_PERIOD) * $::env(IO_PCT) ]
set output_delay_value [ expr $::env(CLOCK_PERIOD) * $::env(IO_PCT) ]
set_max_fanout $::env(MAX_FANOUT_CONSTRAINT) [ current_design ]
set cap_load [ expr $::env(OUTPUT_CAP_LOAD) / 1000.0 ] ;# fF -> pF

# Remove clock net from inputs
set idx [ lsearch [ all_inputs ] "clk" ]
set all_inputs_wo_clk [ lreplace [ all_inputs ] $idx $idx ]

#  clk   clock is generated by the RP2040 chip
create_clock [ get_ports "clk" ]  -name rp2040_clk -period $::env(CLOCK_PERIOD)
#set_input_delay $input_delay_value -clock [ get_clocks rp2040_clk ] $all_inputs_wo_clk
set_output_delay $output_delay_value -clock [ get_clocks rp2040_clk ] [ all_outputs ]
set_clock_uncertainty $::env(SYNTH_CLOCK_UNCERTAINTY) [ get_clocks rp2040_clk ]
set_clock_transition $::env(SYNTH_CLOCK_TRANSITION) [ get_clocks rp2040_clk ]

#  s8b10.clk10   clock is generated internally
create_clock [ get_nets "\s8b10.r_clk10" ]  -name ser_clk -period $::env(CLOCK_PERIOD)
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[0\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[1\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[2\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[3\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[4\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[5\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[6\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "ui_in\[7\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "uio_in\[0\]"
set_input_delay $input_delay_value -clock [ get_clocks ser_clk ] "uio_in\[4\]"
set_clock_uncertainty $::env(SYNTH_CLOCK_UNCERTAINTY) [ get_clocks ser_clk ]
set_clock_transition $::env(SYNTH_CLOCK_TRANSITION) [ get_clocks ser_clk ]

#  d10b8.clk10   clock is generated internally
create_clock [ get_nets "\d10b8.r_clk10" ]  -name des_clk -period $::env(CLOCK_PERIOD)
#set_input_delay $input_delay_value -clock [ get_clocks des_clk ] $all_inputs_wo_clk
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\0\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\1\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\2\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\3\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\4\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\5\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\6\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uo_out[\7\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uio_out[\1\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uio_out[\3\]"
set_output_delay $output_delay_value -clock [ get_clocks des_clk ] "uio_out[\7\]"
set_clock_uncertainty $::env(SYNTH_CLOCK_UNCERTAINTY) [ get_clocks des_clk ]
set_clock_transition $::env(SYNTH_CLOCK_TRANSITION) [ get_clocks des_clk ]

# rp2040_clk  and  fpga_clk  are mesochronous, and they never interact
set_clock_groups -asynchronous -group { rp2040_clk } -group { des_clk }
set_clock_groups -asynchronous -group { rp2040_clk } -group { ser_clk }
set_clock_groups -asynchronous -group { des_clk } -group { ser_clk }

# Miscellanea
set_driving_cell -lib_cell $::env(SYNTH_DRIVING_CELL) -pin $::env(SYNTH_DRIVING_CELL_PIN) $all_inputs_wo_clk
set_load  $cap_load [ all_outputs ]
set_timing_derate -early [ expr {1-$::env(SYNTH_TIMING_DERATE)} ]
set_timing_derate -late [ expr {1+$::env(SYNTH_TIMING_DERATE)} ]

